name: lab1
version: 1.0.0+1
description: Simple Flutter app demonstrating FizzBuzz and reverse list.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
