name: lab3
version: 1.0.0+1
description: Flutter app with Stack layout and animated text transitions.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
